# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**"
    - "db/**/*"
    - "spec/**/*"
    - "config/**/*"
    - "**/vendor/**/*"
    - "**/vendor/**/.*"
    - "node_modules/**/*"

# LAYOUT
Layout/LineLength:
  Max: 200

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

# LINT
Lint/RedundantStringCoercion:
  Enabled: true

# STYLE
Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

# METRICS
Metrics/ModuleLength:
  Max: 1000

Metrics/ClassLength:
  Max: 1000

Metrics/MethodLength:
  Max: 36

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 16

Metrics/AbcSize:
  Max: 36
